# Generated by Django 5.1.1 on 2024-10-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject1',
            old_name='teacher',
            new_name='faculty',
        ),
    ]
