# Generated by Django 5.1.1 on 2024-10-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_teacher_subject1_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class1',
            old_name='name',
            new_name='Semester',
        ),
    ]
