# Generated by Django 5.1.1 on 2024-11-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_name_class1_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetableentry1',
            old_name='teacher',
            new_name='faculty',
        ),
    ]
