# Generated by Django 5.1.1 on 2024-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('INSTITUTE', 'Institute'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], max_length=20),
        ),
    ]
