# Generated by Django 5.1.1 on 2024-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('LABSTAFF', 'Labstaff'), ('STUDENT', 'student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
