# Generated by Django 5.1.1 on 2024-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('FACULTY', 'Faculty'), ('LABSTAFF', 'Labstaff'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
