# Generated by Django 5.1.1 on 2024-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('LABSTAFF', 'Labstaff'), ('STUDENT', 'student'), ('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], max_length=20),
        ),
    ]
