# Generated by Django 5.1.1 on 2025-02-10 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0020_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('FACULTY', 'Faculty'), ('LABSTAFF', 'Labstaff'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
